name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 12 * * 1"  # weekly Monday noon UTC

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  USE_GITHUB_DATA: "true"
  # Change or remove if you don't use Medium:
  MEDIUM_USERNAME: "AryamanJ26"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Install deps (prefer lockfile if present)
      - name: Install
        run: npm ci || npm install

      # Build the site. If fetch.js needs a token, pass a secret here ONLY.
      - name: Build
        run: node fetch.js && npm run build
        env:
          # OPTIONAL: create a PAT with minimal scopes (read-only public) as a repo secret like PUBLIC_GH_TOKEN
          # and use that here. Avoid injecting ${{ secrets.GITHUB_TOKEN }} into the client app.
          REACT_APP_GITHUB_TOKEN: ${{ secrets.PUBLIC_GH_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
